import { gsap, reduced, picture, arrow, label } from '../shared';
export function comparatore(){
 const el=document.querySelector('#volume');
 el.innerHTML=`${label('02','Dal tratto al volume')}<div class="section-heading"><h2 id="compare-title">Trascina<br>la matita<span class="accent-text">.</span></h2><span class="hand">guarda lo schizzo<br>diventare casa ${arrow('down')}</span></div><div class="compare-layout"><div class="compare-side"><span class="mono">Una linea è già una possibilità.</span><p>Prima immaginiamo.<br>Poi diamo forma.</p><span class="hand">Lo stesso spazio.<br>Due modi di vederlo.</span><svg class="side-drawing" viewBox="0 0 160 100" fill="none" stroke="currentColor" aria-hidden="true"><path d="M6 85h145M20 85V26h100v59M12 26h129M20 38h100M31 39v46M75 39v46M89 52h19v33M22 21h100M22 17v8m100-8v8M132 26v59m-4-59h8m-8 59h8"/></svg><span class="mono">Fig. 02 / La stessa casa,<br>prima e dopo il primo segno.</span></div><div class="compare-main"><div class="compare-frame" data-cursor="Trascina"><div class="compare-sketch">${picture('fronte-schizzo','Schizzo a matita di una villa con portale bianco, vetrate e piscina')}<div class="compare-notes" aria-hidden="true"><span class="note-level">+7.20</span><span class="note-wood">soffitto in legno di iroko</span><span class="note-glass">vetrate scorrevoli</span><span class="note-pool">vasca a sfioro</span><span class="note-stair">scala in pietra</span></div></div><div class="compare-photo">${picture('fronte','La stessa villa realizzata, con soffitto in legno e piscina a sfioro')}</div><div class="compare-divider"><span class="handle" aria-hidden="true"><svg viewBox="0 0 28 20" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m10 5-5 5 5 5m8-10 5 5-5 5M14 2v16"/></svg></span></div><div class="compare-corner mono" aria-hidden="true"><span>Schizzo</span><span>Materia</span></div><label for="comparison" class="visually-hidden">Percentuale di foto visibile, da solo schizzo a solo render</label><input id="comparison" type="range" min="0" max="100" value="50" aria-valuetext="50% foto, 50% schizzo"></div><div class="compare-controls"><span class="mono">Disegno ↔ Realtà</span><div class="compare-presets" role="group" aria-label="Scegli la vista del comparatore"><button data-value="0" aria-pressed="false">Solo schizzo</button><button data-value="50" aria-pressed="true">Metà e metà</button><button data-value="100" aria-pressed="false">Solo render</button></div></div></div></div>`;
 const frame=el.querySelector('.compare-frame'),range=el.querySelector('input'),photo=el.querySelector('.compare-photo'),notes=el.querySelector('.compare-notes'),divider=el.querySelector('.compare-divider'),buttons=el.querySelectorAll('[data-value]');
 function update(value){value=Math.min(100,Math.max(0,Number(value)));range.value=value;photo.style.clipPath=`inset(0 0 0 ${100-value}%)`;notes.style.clipPath=`inset(0 ${value}% 0 0)`;divider.style.transform=`translateX(${frame.clientWidth*(100-value)/100}px)`;range.setAttribute('aria-valuetext',`${value}% foto, ${100-value}% schizzo`);buttons.forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.value)===value));}
 range.addEventListener('input',()=>update(range.value));
 buttons.forEach(b=>b.addEventListener('click',()=>update(b.dataset.value)));
 let dragging=false;
 function point(e){const r=frame.getBoundingClientRect();update(Math.round((1-(e.clientX-r.left)/r.width)*100));}
 frame.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragging=true;frame.setPointerCapture(e.pointerId);range.focus({preventScroll:true});point(e);});
 frame.addEventListener('pointermove',e=>{if(dragging)point(e);});frame.addEventListener('pointerup',()=>dragging=false);frame.addEventListener('pointercancel',()=>dragging=false);
 new ResizeObserver(()=>update(range.value)).observe(frame);
 update(50);
 if(!reduced)gsap.from(frame,{scale:.86,borderRadius:40,duration:1.2,ease:'power3.out',scrollTrigger:{trigger:frame,start:'top 85%',once:true}});
}
