import { label, arrow, reveal } from '../shared';
export function contatti(){
 const el=document.querySelector('#contatti');
 el.innerHTML=`${label('06','Cominciamo da qui')}<div class="contact-layout"><div class="contact-copy"><h2 id="contact-title">Disegniamo<br>la tua prossima<br><span class="accent-text">casa.</span></h2><span class="hand">Basta un’idea.<br>Al resto, pensiamo insieme.</span><p>Una nuova casa, uno spazio da ripensare,<br>una domanda ancora senza forma.<br>Raccontacela.</p><address><span class="mono">Vieni a trovarci</span><p>[INDIRIZZO STUDIO]<br>[CITTÀ]</p><span class="mono">Oppure scrivici</span><p>[EMAIL]<br>[TELEFONO]</p></address></div><div class="contact-form-wrap"><div class="form-caption mono"><span>Il primo schizzo</span><span>N. 001</span></div><form name="primo-schizzo" class="contact-form" method="POST" data-netlify="true" netlify-honeypot="website" novalidate><input type="hidden" name="form-name" value="primo-schizzo"><div class="visually-hidden" aria-hidden="true"><label>Lascia vuoto questo campo<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="form-field"><label for="nome">Come ti chiami?<span class="mono">01 / Nome *</span></label><input id="nome" name="nome" type="text" placeholder="Il tuo nome" autocomplete="name" required maxlength="120" aria-describedby="nome-error"><span id="nome-error" class="field-error"></span></div><div class="form-field"><label for="email">Dove possiamo scriverti?<span class="mono">02 / Email *</span></label><input id="email" name="email" type="email" placeholder="La tua email" autocomplete="email" required maxlength="254" aria-describedby="email-error"><span id="email-error" class="field-error"></span></div><div class="form-field"><label for="progetto">A cosa stai pensando?<span class="mono">03 / Tipo di progetto *</span></label><select id="progetto" name="progetto" required aria-describedby="progetto-error"><option value="">Scegli il tuo progetto</option><option>Nuova casa</option><option>Ristrutturazione</option><option>Spazio culturale</option><option>Altro progetto</option></select><span id="progetto-error" class="field-error"></span></div><div class="form-field"><label for="idea">Ogni idea merita una linea.<span class="mono">04 / La tua idea *</span></label><textarea id="idea" name="idea" rows="3" placeholder="Raccontaci il tuo spazio, i tuoi desideri, le tue domande." required minlength="10" maxlength="5000" aria-describedby="idea-error"></textarea><span id="idea-error" class="field-error"></span></div><div class="form-bottom"><span class="mono">* Campi obbligatori</span><p>Usiamo i tuoi dati per rispondere a questa richiesta.</p><button class="pill primary" type="submit">Invia il primo schizzo ${arrow()}</button></div><p class="form-status" role="status" aria-live="polite"></p></form></div></div>`;
 const form=el.querySelector('.contact-form'),status=el.querySelector('.form-status'),submit=form.querySelector('button'),fields=[...form.querySelectorAll('[required]')];
 function validate(field){const good=field.checkValidity()&&(field.type==='email'||field.tagName==='SELECT'||field.value.trim().length>=(field.name==='idea'?10:1));const error=el.querySelector(`#${field.id}-error`);field.setAttribute('aria-invalid',!good);error.textContent=good?'':field.name==='email'?'Inserisci un indirizzo email valido.':field.name==='progetto'?'Scegli un tipo di progetto.':field.name==='idea'?'Raccontaci la tua idea in almeno 10 caratteri.':'Inserisci il tuo nome.';return good;}
 fields.forEach(f=>f.addEventListener('input',()=>{if(f.getAttribute('aria-invalid')==='true')validate(f);}));
 form.addEventListener('submit',async e=>{
  e.preventDefault();status.textContent='';const invalid=fields.filter(f=>!validate(f));if(invalid.length){status.textContent='Controlla i campi evidenziati prima di inviare.';invalid[0].focus();return;}
  if(form.elements.website.value)return;
  const endpoint=import.meta.env.VITE_CONTACT_ENDPOINT;
  const netlify=__NETLIFY__||import.meta.env.VITE_NETLIFY_FORMS==='true';
  if(!endpoint&&!netlify){status.textContent='Il modulo non è ancora collegato. Nessun messaggio è stato inviato. Sarà attivo dopo la pubblicazione su Netlify o la configurazione dell’endpoint.';return;}
  submit.disabled=true;submit.textContent='Invio in corso…';
  try{
   const data=new URLSearchParams(new FormData(form));const response=await fetch(endpoint||'/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:data});
   if(!response.ok)throw Error('invio');form.reset();status.textContent='Il tuo primo schizzo è arrivato. Grazie, ti risponderemo presto.';
  }catch{status.textContent='Non è stato possibile inviare il messaggio. Riprova tra poco.';}
  finally{submit.disabled=false;submit.innerHTML=`Invia il primo schizzo ${arrow()}`;}
 });
 reveal(el.querySelectorAll('.contact-copy h2,.contact-copy>.hand,.contact-form-wrap'),el);
}
