import { gsap, reduced, picture, arrow, label } from '../shared';
import construction from '../data/villa-lines.json';
export function hero(){
 const el=document.querySelector('#hero');
 const words=['Ogni','casa','comincia','da','una','linea.'];
 if(!el.querySelector('.hero-copy')) el.innerHTML=`<div class="hero-copy">${label('00','Studio di architettura · [CITTÀ]')}<h1 id="hero-title">${words.map((w,i)=>`<span class="word-mask ${i===5?'accent-word':''}"><span class="hero-word">${w}</span>${i===5?`<svg class="brush" viewBox="0 0 300 20" aria-hidden="true"><path d="M4 11C69 0 154 3 295 9M8 16C107 7 217 10 279 13" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`:''}</span>`).join(' ')}</h1><div class="hero-description"><p>Ascoltiamo le persone.<br>Disegniamo lo spazio che le somiglia.</p><p class="hero-small">Case da abitare, prima che da guardare.<br>Dal primo segno all’ultima luce.</p></div><div class="hero-actions"><a class="pill primary" href="#entra">Entra in casa ${arrow('down')}</a><a class="text-link" href="#contatti">Raccontaci la tua idea ${arrow()}</a></div></div><div class="hero-art"><div class="drawing-meta mono"><span>Fig. 01 / Dalla linea alla casa</span><span>Scala 1 : 100</span></div><div class="hero-frame" role="img" aria-label="Una villa contemporanea passa dallo schizzo al volume, alla materia e alla luce"><div class="hero-layer hero-color">${picture('villa','Villa bianca con terrazza in vetro, pietra locale e piscina', {hero:true,sizes:'(max-width: 760px) 100vw, 53vw'})}</div><div class="hero-layer hero-volume">${picture('villa','',{hero:true})}</div><div class="hero-layer hero-sketch">${picture('villa-schizzo','',{hero:true})}</div><svg class="construction-lines" viewBox="${construction.viewBox}" aria-hidden="true">${construction.lines.map(([a,b,c,d])=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}"/>`).join('')}</svg><div class="hero-pencil"></div><div class="hero-light-thread"></div><div class="warm-light"></div><div class="hero-annotations" aria-hidden="true"><span class="annotation dimension">15.80 m <i></i></span><span class="annotation terrace">terrazza in vetro <svg viewBox="0 0 80 50"><path d="M5 5Q65 0 68 40M56 31l12 9 6-14"/></svg></span><span class="annotation stone">pietra locale</span><span class="annotation portal">portale bianco</span><span class="annotation water">acqua, specchio del cielo <svg viewBox="0 0 80 50"><path d="M5 5Q65 0 68 40M56 31l12 9 6-14"/></svg></span></div><span class="frame-cross top" aria-hidden="true">+</span><span class="frame-cross bottom" aria-hidden="true">+</span></div><div class="hero-phases mono">${['Schizzo','Volume','Materia','Luce'].map((x,i)=>`<span class="phase ${i===0?'is-active':''}"><b>0${i+1}</b> ${x}</span>`).join('')}</div><div class="art-note hand">Il futuro ha ancora<br>il segno di una matita.<svg viewBox="0 0 100 60" aria-hidden="true"><path d="M90 54Q10 60 15 5m-8 10 8-10 9 9"/></svg></div></div><div class="hero-bottom mono"><a href="#entra">Scorri. C’è una casa da scoprire <span aria-hidden="true">↓</span></a><span>Ascolto · Disegno · Architettura</span><span class="hero-coordinate">45° 27′ N / 09° 11′ E</span></div>`;
 const drawing=el.querySelector('.construction-lines');drawing.setAttribute('viewBox',construction.viewBox);drawing.innerHTML=construction.lines.map(([a,b,c,d])=>`<line x1="${a}" y1="${b}" x2="${c}" y2="${d}"/>`).join('');
 const color=el.querySelector('.hero-color');const saturated=document.createElement('div');saturated.className='hero-saturated';saturated.append(color.querySelector('picture').cloneNode(true));color.append(saturated);
 const phases=el.querySelectorAll('.phase');const choose=i=>phases.forEach((p,j)=>p.classList.toggle('is-active',i===j));
 if(reduced){gsap.set('.hero-volume,.hero-sketch,.construction-lines,.hero-annotations,.hero-pencil,.hero-light-thread',{opacity:0});gsap.set(saturated,{opacity:1});choose(3);return()=>{};}
 const lines=el.querySelectorAll('.construction-lines line');lines.forEach(l=>{const length=Math.hypot(l.x2.baseVal.value-l.x1.baseVal.value,l.y2.baseVal.value-l.y1.baseVal.value);gsap.set(l,{strokeDasharray:length,strokeDashoffset:length});});
 const cycle=gsap.timeline({repeat:-1,paused:true});
 cycle.set('.hero-sketch',{opacity:1,clipPath:'inset(0 100% 0 0)'},0).set('.hero-color',{opacity:0,clipPath:'inset(0 100% 0 0)'},0).set('.hero-volume',{opacity:0},0).set('.hero-annotations,.construction-lines',{opacity:0},0).set('.hero-pencil',{opacity:1,x:0},0).set('.warm-light,.hero-saturated',{opacity:0},0).call(()=>choose(0),null,0)
 .to('.hero-sketch',{clipPath:'inset(0 0% 0 0)',duration:3.96,ease:'none'},0).to('.hero-pencil',{x:()=>el.querySelector('.hero-frame').clientWidth,duration:3.96,ease:'none'},0).to(lines,{strokeDashoffset:0,duration:1.3,stagger:{amount:2.1},ease:'power1.out'},.4).to('.construction-lines,.hero-annotations',{opacity:1,duration:.5},.5).to('.hero-pencil',{opacity:0,duration:.3},3.96)
 .call(()=>choose(1),null,4.68).to('.hero-volume',{opacity:.55,duration:1.3},4.68).to('.hero-annotations,.construction-lines',{opacity:0,duration:.6},4.68)
 .call(()=>choose(2),null,8.28).set('.hero-color',{opacity:1},8.28).set('.hero-light-thread',{opacity:1,x:0},8.28).to('.hero-color',{clipPath:'inset(0 0% 0 0)',duration:2.16,ease:'none'},8.28).to('.hero-light-thread',{x:()=>el.querySelector('.hero-frame').clientWidth,duration:2.16,ease:'none'},8.28).to('.hero-light-thread',{opacity:0,duration:.2},10.44)
 .call(()=>choose(3),null,11.16).to('.warm-light',{opacity:.5,duration:2},11.16).to(saturated,{opacity:1,duration:4.68,ease:'none'},11.16).to('.hero-sketch,.hero-volume',{opacity:0,duration:.4},11.16)
 .to('.hero-color,.warm-light',{opacity:0,duration:1.44},16.56).set(lines,{strokeDashoffset:i=>Math.hypot(lines[i].x2.baseVal.value-lines[i].x1.baseVal.value,lines[i].y2.baseVal.value-lines[i].y1.baseVal.value)},18);
 const observer=new IntersectionObserver(([entry])=>entry.isIntersecting&&el.dataset.started?cycle.play():cycle.pause(),{threshold:.05});observer.observe(el);
 gsap.utils.toArray('.brush path').forEach(path=>{const len=path.getTotalLength();gsap.fromTo(path,{strokeDasharray:len,strokeDashoffset:len},{strokeDashoffset:0,duration:1.4,repeat:-1,repeatDelay:5,ease:'power2.out'});});
 return ()=>{el.dataset.started='true';gsap.from('.hero-word',{yPercent:112,rotation:4,duration:1.1,stagger:.08,ease:'power4.out'});gsap.from('.hero-description,.hero-actions,.hero-bottom',{y:25,opacity:0,duration:1,stagger:.12,delay:.5});gsap.from('.hero-frame',{clipPath:'inset(22% 16%)',scale:.92,rotation:-1.5,duration:1.5,ease:'power4.out',delay:.25});cycle.play();};
}
